# This workflow will build and unit test the project.
# If the workflow is running on the "master" branch, then
# semantic-release is also run to create a new release (if
# warranted by the new commits being built).

name: build

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    # Allow workflow to be triggered manually.

jobs:
  build:
    name: build-test (java ${{matrix.java-version}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['11', '17']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java ${{matrix.java-version}}
        uses: actions/setup-java@v4 
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
          cache: 'maven'

      - name: Build & Test
        run: mvn -B clean verify -fae -DskipITs

  create-release:
    needs: build
    name: semantic-release
    if: github.ref_name == 'master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Publishing Tools
        run: |
          pip install bump-my-version
          npm install

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run semantic-release