name: CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  MVN_ARGS: "--settings .github/maven-settings.xml"

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Set Maven version
      run: ./build/setMavenVersion.sh

    - name: Build and test
      run: mvn verify -fae -DskipITs ${{ env.MVN_ARGS }}
      
    - name: Echo success
      run: echo "Build is successful"

  release-and-publish:
    needs: build-test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ci
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        # Configure ~/.m2/settings.xml for Central Publishing
        server-id: central
        server-username: CP_USERNAME
        server-password: CP_PASSWORD
        # Import GPG key into build agent's local keystore
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: |
        sudo apt-get update
        npm install -g npm@latest || npm install -g npm@9
        pip install bump2version
        npm install --save-dev \
          semantic-release@latest \
          @semantic-release/changelog@latest \
          @semantic-release/exec@latest \
          @semantic-release/git@latest \
          @semantic-release/github@latest

    - name: Release and Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # Updated environment variables for Central Publishing
        CP_USERNAME: ${{ secrets.CP_USERNAME }}
        CP_PASSWORD: ${{ secrets.CP_PASSWORD }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
      run: |
        # Setup GPG first
        ./build/setupSigning.sh
        
        # Run semantic-release to tag
        npx semantic-release
        if [ $? -eq 0 ]; then
          echo "Semantic release has successfully created a new tagged-release"

          # Fetch the new tag
          git fetch --tags

          # Get latest tag
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is: $TAG"
          
          # Set version using tag directly
          mvn versions:set -DnewVersion=${TAG} -DgenerateBackupPoms=false
          
          # Now deploy with the release version using central profile
          if mvn deploy -X ${{ env.MVN_ARGS }} -DskipTests -P central; then
            echo "Maven artifacts successfully published to Maven Central via Central Publishing!"
            echo "Publishing javadoc..."
            mvn clean javadoc:aggregate ${{ env.MVN_ARGS }}
            ./build/publishJavadoc.sh
            echo "Javadocs successfully published to gh-pages!"
          else
            echo "Maven deployment failed"
            exit 1
          fi
        else
          echo "Semantic release failed"
          exit 1
        fi